### ISSUE TITLE
Automate OVS bridge deployment

### ISSUE THREAD

**Issue by soessa** [k8snetworkplumbingwg/ovs-cni#181]
Hi,

We are using ovs-cni inside our Kubernetes cluster and we were wondering if there was any known way to automate OVS bridges deployments as a pod get "attached" to an OVS bridge. As far as I know, it doesn't seem to be available with ovs-cni but will it be a next feature or not at all ? 

Thanks.

**Comment by phoracek** [comment]
Hello,

Host network configuration is out of scope of the CNI, as it should be only focused on the attachment to an existing resource.

That being said, would https://github.com/nmstate/kubernetes-nmstate/ work for you? It is an add-on for Kubernetes that allows you to configure host networking through Kubernetes API. Its only dependency is reasonably new version of NetworkManager running on your nodes.

See installation guide on https://github.com/nmstate/kubernetes-nmstate/releases/tag/v0.50.0.

The configuration to create an OVS bridge would then look something like this:

```yaml
apiVersion: nmstate.io/v1beta1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: ovs-bridge-iface
spec:
  desiredState:
    interfaces:
      - name: ovs0
        type: ovs-interface
        state: up
      - name: br1
        description: ovs bridge with eth1 as a port and ovs0 as an internal interface
        type: ovs-bridge
        state: up
        bridge:
          options:
            stp: true
          port:
            - name: eth1
            - name: ovs0
```
