### ISSUE TITLE
IP addresses duplicate on two pods running on different nodes

### ISSUE THREAD

**Issue by yockgen** [k8snetworkplumbingwg/ovs-cni#222]
Hi,
Need help,  IP address found duplicate on two pods running on different nodes as below:
===================================================================================
root@tgl02:/home/yockgenm/ovs-cni# kubectl exec -it test01-deployment-866cf959f5-n7nvq -- ip a
......
7: eth0@if56: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1480 qdisc noqueue state UP
    link/ether 1a:ce:62:38:5a:f1 brd ff:ff:ff:ff:ff:ff
    inet 192.168.231.196/32 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::18ce:62ff:fe38:5af1/64 scope link
       valid_lft forever preferred_lft forever
8: net1@if57: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP
    link/ether 0a:58:c0:a8:01:ca brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.202/24 brd 192.168.1.255 scope global net1 **<-ERR: IP address duplicate**
       valid_lft forever preferred_lft forever
    inet6 fe80::5c13:31ff:fef7:c7d4/64 scope link
       valid_lft forever preferred_lft forever
	   
root@tgl02:/home/yockgenm/ovs-cni# kubectl exec -it test01-deployment-866cf959f5-xcsb7 -- ip a
............
7: eth0@if220: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1480 qdisc noqueue state UP
    link/ether a6:a8:2c:e1:01:dc brd ff:ff:ff:ff:ff:ff
    inet 192.168.156.74/32 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::a4a8:2cff:fee1:1dc/64 scope link
       valid_lft forever preferred_lft forever
8: net1@if221: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP
    link/ether 0a:58:c0:a8:01:ca brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.202/24 brd 192.168.1.255 scope global net1 **<-ERR: IP address duplicate**
       valid_lft forever preferred_lft forever
    inet6 fe80::9477:f0ff:feb9:be01/64 scope link
       valid_lft forever preferred_lft forever

pods info
----------
NAME                                 READY   STATUS    RESTARTS   AGE   IP                NODE    NOMINATED NODE   READINESS GATES
test01-deployment-866cf959f5-n7nvq   1/1     Running   0          37m   192.168.231.196   tgl02   <none>           <none>
test01-deployment-866cf959f5-qhzvt   1/1     Running   0          37m   192.168.156.73    kbl01   <none>           <none>
test01-deployment-866cf959f5-xcsb7   1/1     Running   0          37m   192.168.156.74    kbl01   <none>           <none>

network attachment definition
---------------------------------
```
cat <<EOF | kubectl create -f -
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ovs-conf
  annotations:
    k8s.v1.cni.cncf.io/resourceName: ovs-cni.network.kubevirt.io/br1
spec:
  config: '{
      "cniVersion": "0.4.0",
      "type": "ovs",
      "bridge": "ovs-br1",
      "vlan": 100,
	  "ipam": {
        "type": "host-local",
        "subnet": "192.168.1.0/24",
        "rangeStart": "192.168.1.201",
        "rangeEnd": "192.168.1.250",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "gateway": "192.168.1.1"
      }
    }'
EOF
```

pod deployment
-------------------
```
cat <<EOF | kubectl create -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test01-deployment
  labels:
    app: yockgen
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test01pod
  template:
    metadata:      
      annotations:
        k8s.v1.cni.cncf.io/networks: ovs-conf
      labels:
        app: test01pod
    spec:
      containers:
      - name: test01pod
        command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
        image: alpine
        securityContext:
          capabilities:
            add: ["NET_ADMIN", "SYS_TIME","NET_RAW"]
EOF
```
