### ISSUE TITLE
OVS-cni installation in OpenShift

### ISSUE THREAD

**Issue by ydguala** [k8snetworkplumbingwg/ovs-cni#277]
**What happened**:
Using de Cluster Network Addons Operator (CNAO) to install ovs-cni is not working

**What you expected to happen**:
ovs-cni installed

**How to reproduce it (as minimally and precisely as possible)**:
install according instructions:

https://github.com/kubevirt/cluster-network-addons-operator#open-vswitch 

**Anything else we need to know?**:
In OpenShift 4.13 with OpenShift Virtualization, the ovs-cni installation is managed by the hyperconverged cluster operator (HCO) in an annotation in the HyperConverged objects:
 
https://github.com/kubevirt/hyperconverged-cluster-operator/blob/main/docs/cluster-configuration.md#ovs-opt-in-annotation

```YAML
apiVersion: hco.kubevirt.io/v1beta1
kind: HyperConverged
metadata:
  annotations:
    deployOVS: "true"
...
```
**Environment**:
